name: hng_task3
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # To simply access the toString() method of classes as it compares items
  equatable: ^2.0.5

  # Use for connecting app with newtwork
  http: ^0.13.5

  # A flutter implementation of React hooks.
  flutter_hooks: ^0.18.3

  # A simple way to access state from anywhere in your app
  hooks_riverpod: ^1.0.3

  # Different text style font family found in google
  google_fonts: 2.2.0

  #A package provides an easy way to add shimmer effect in Flutter project
  shimmer: ^2.0.0

  #A flutter ListView in which list items can be grouped to sections.
  grouped_list: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
